name: CI/CD com Flask e Robot Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install Flask robotframework robotframework-seleniumlibrary webdriver_manager

    - name: Iniciar Aplicação Flask em Background
      run: |
        python app.py & # O '&' faz o comando rodar em segundo plano
        sleep 5 # Dá um tempo para o servidor Flask iniciar completamente

    - name: Executar Testes Robot Framework
      run: |
        cd tests # Navega para a pasta onde estão seus testes
        robot ecommerce.robot # Executa os testes

    - name: Upload de Relatórios de Teste (Opcional)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-test-reports
        path: tests/*.html